######################## default configuration ####################
baseURL = "/"
title = "Epicurus"
# theme = "redlab-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "redlab" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific.popup.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

############################## navigation ###############################
[[menu.main]]
name = "About Us"
URL = ""
weight = 2

[[menu.main]]
weight = 3
name = "Blogs"
hasChildren = true

[[menu.main]]
weight = 4
name = "Products"
hasChildren = true


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@redlab.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search
search = true
target_url = "https://itg-investments.com/"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Sign Up"
link = "#"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


###################### Clients logo slider ###############################
[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-1.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-2.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-3.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-4.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-5.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-1.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-2.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-3.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-4.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-5.png"

############################# social icon #################################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Multifunctional platform, your one-stop tool. Created specifically for investors and traders who strive to achieve financial success."


